# Generated by Django 5.2.7 on 2025-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_order_products_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
