# Generated by Django 5.2.7 on 2025-12-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_status_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_order',
            new_name='price_at_checkout',
        ),
    ]
