# Generated by Django 5.2.7 on 2026-01-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='max_user',
            new_name='max_users',
        ),
    ]
