# Generated by Django 5.2.7 on 2026-02-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_joinrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('user', 'company')},
        ),
        migrations.DeleteModel(
            name='CompanyManager',
        ),
    ]
