# Generated by Django 5.2.7 on 2026-02-05 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_joinrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
