# Generated by Django 5.2.7 on 2026-02-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_company_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='company',
            name='managers',
        ),
        migrations.CreateModel(
            name='CompanyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
