# Generated by Django 5.2.7 on 2026-02-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_joinrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companymanager',
            unique_together={('user', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('user', 'company')},
        ),
    ]
