# Generated by Django 5.2.7 on 2026-02-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_companymanager_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='company',
            name='bankdetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankdetails'),
        ),
    ]
