# Generated by Django 5.2.7 on 2025-10-31 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('grn_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date_returned', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grn.customer')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grn.customer')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('type_of_good', models.CharField(choices=[('motor', 'motor'), ('vsd', 'VSD'), ('other', 'Other')], max_length=100)),
                ('urgency', models.CharField(choices=[('not_urgent', 'Not Urgent'), ('urgent', 'Urgent')], default='not_urgent', max_length=50)),
                ('status', models.CharField(choices=[('awaiting_request', 'Awaiting Request'), ('test_and_report', 'Test & Report'), ('awaiting_client', 'Awaiting Client'), ('sent_for_repair', 'Sent for repair'), ('repairing', 'Repairing'), ('awaiting_parts', 'Awaiting parts'), ('awaiting_po', 'Awaiting PO'), ('out_for_delivery', 'Out for delivery'), ('awaiting_collection', 'Awaiting Collection')], max_length=50)),
                ('location', models.CharField(choices=[('grn_section', 'GRN Section'), ('test_bay', 'Test Bay'), ('technicians_racks', 'Technicians racks'), ('dispatch_area', 'Dispatch Area'), ('out_for_delivery', 'Out for delivery')], max_length=100)),
                ('reason_for_return', models.CharField(choices=[('credit', 'Credit'), ('test_and_report', 'Test & Report'), ('return', 'Return')])),
                ('credit_request_reason', models.TextField(blank=True, null=True)),
                ('job_card_number', models.CharField(max_length=100)),
                ('report_quote_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_order_number', models.CharField(max_length=100)),
                ('invoice_credit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_note', models.CharField(max_length=100)),
                ('invoice_credit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_returned', models.DateField()),
                ('credit_passed_date', models.DateField(blank=True, null=True)),
                ('original_invoice_date', models.DateField(blank=True, null=True)),
                ('days_in_warehouse', models.IntegerField(blank=True, null=True)),
                ('days_awaiting_us', models.IntegerField(blank=True, null=True)),
                ('days_awaiting_client', models.IntegerField(blank=True, null=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grn.grn')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
