# Generated by Django 5.2.7 on 2025-11-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0001_initial_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='customer',
        ),
        migrations.AddField(
            model_name='grn',
            name='contact_person_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='grn.contactperson'),
            preserve_default=False,
        ),
    ]
