# Generated by Django 5.2.7 on 2025-11-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0002_remove_grn_customer_grn_contact_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grn',
            old_name='contact_person_id',
            new_name='contact_person',
        ),
    ]
