# Generated by Django 5.2.7 on 2025-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0003_rename_contact_person_id_grn_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='farm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
