# Generated by Django 5.2.7 on 2025-11-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0004_customer_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsitem',
            name='urgency',
        ),
        migrations.AddField(
            model_name='goodsitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsitem',
            name='urgent',
            field=models.CharField(choices=[('not_urgent', 'Not Urgent'), ('urgent', 'Urgent')], default='not_urgent', max_length=10),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='reason_for_return',
            field=models.CharField(choices=[('credit', 'Credit'), ('test_and_report', 'Test & Report'), ('return', 'Return')], max_length=50),
        ),
    ]
