# Generated by Django 5.2.7 on 2025-11-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0005_remove_goodsitem_urgency_goodsitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='farm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
