# Generated by Django 5.2.7 on 2025-11-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0006_alter_customer_branch_alter_customer_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='customer_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='dispatch_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='job_card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='location',
            field=models.CharField(choices=[('grn_section', 'GRN Section'), ('test_bay', 'Test Bay'), ('technicians_racks', 'Technicians racks'), ('dispatch_area', 'Dispatch Area'), ('out_for_delivery', 'Out for delivery')], default='awaiting_request', max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='reason_for_return',
            field=models.CharField(choices=[('credit', 'Credit'), ('test_and_report', 'Test & Report'), ('return', 'Return')], default='awaiting_request', max_length=50),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='status',
            field=models.CharField(choices=[('awaiting_request', 'Awaiting Request'), ('test_and_report', 'Test & Report'), ('awaiting_client', 'Awaiting Client'), ('sent_for_repair', 'Sent for repair'), ('repairing', 'Repairing'), ('awaiting_parts', 'Awaiting parts'), ('awaiting_po', 'Awaiting PO'), ('out_for_delivery', 'Out for delivery'), ('awaiting_collection', 'Awaiting Collection')], default='awaiting_request', max_length=50),
        ),
    ]
