# Generated by Django 5.2.7 on 2025-11-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0007_alter_goodsitem_customer_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsitem',
            name='date_returned',
        ),
    ]
