# Generated by Django 5.2.7 on 2025-11-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0008_remove_goodsitem_date_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_item', to='grn.grn'),
        ),
    ]
