# Generated by Django 5.2.7 on 2025-11-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0009_alter_goodsitem_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(default='kobus.vs.2006@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
