# Generated by Django 5.2.7 on 2025-11-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0010_contactperson_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='type_of_good',
            field=models.CharField(choices=[('motor', 'Motor'), ('vsd', 'VSD'), ('other', 'Other')], max_length=100),
        ),
    ]
