# Generated by Django 5.2.7 on 2025-11-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0011_alter_goodsitem_type_of_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='reason_for_return',
            field=models.CharField(choices=[('credit', 'Credit'), ('test_and_report', 'Test & Report'), ('return', 'Return'), ('other', 'Other')], default='Other', max_length=50),
        ),
    ]
