# Generated by Django 5.2.7 on 2025-11-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0012_alter_goodsitem_reason_for_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='location',
            field=models.CharField(choices=[('grn_section', 'GRN Section'), ('test_bay', 'Test Bay'), ('technicians_racks', 'Technicians racks'), ('dispatch_area', 'Dispatch Area'), ('out_for_delivery', 'Out for delivery')], default='grn_section', max_length=100),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='reason_for_return',
            field=models.CharField(choices=[('credit', 'Credit'), ('test_and_report', 'Test & Report'), ('return', 'Return'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
