# Generated by Django 5.2.7 on 2025-11-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0013_alter_goodsitem_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='customer',
            new_name='company',
        ),
    ]
