# Generated by Django 5.2.7 on 2025-11-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0014_rename_customer_contactperson_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsitem',
            name='days_in_warehouse',
        ),
    ]
