# Generated by Django 5.2.7 on 2025-10-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='urgency',
            field=models.CharField(choices=[('not_urgent', 'Not Urgent'), ('urgent', 'Urgent')], default='not_urgent', max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='reason_for_return',
            field=models.CharField(choices=[('credit', 'Credit'), ('test_and_report', 'Test & Report'), ('return', 'Return')]),
        ),
    ]
