"""
Django settings for vsi_business project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import environ

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="8ht6^f%*%d(=-@shjo8&*o)x$o#2ptc#pc^b19_ny7@2_4)(@8",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TESTING = False

ALLOWED_HOSTS = ["*"]

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# Application definition

LOCAL_APPS = [
    "apps.accounts",
    "apps.sales",
]

THIRD_PARTY_APPS = [
    "allauth",
    "allauth.account",
    "django_celery_beat",
    "django_tables2",
    "phonenumber_field"
]

INSTALLED_APPS = (
    [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "django.forms",
        "compressor",
    ]
    + LOCAL_APPS
    + THIRD_PARTY_APPS
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "vsi_business.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.user_group_flags",
                "apps.sales.context_processors.user_info",
            ],
        },
    },
]

WSGI_APPLICATION = "vsi_business.wsgi.application"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if "DATABASE_URL" in env:
    DATABASES = {"default": env.db()}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": env("DJANGO_DATABASE_NAME", default="vsi_business"),
            "USER": env("DJANGO_DATABASE_USER", default="postgres"),
            "PASSWORD": env("DJANGO_DATABASE_PASSWORD", default="postgres"),
            "HOST": env("DJANGO_DATABASE_HOST", default="localhost"),
            "PORT": env("DJANGO_DATABASE_PORT", default="5432"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Johannesburg"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = STATIC_ROOT
# COMPRESS_ROOT = STATIC_ROOT

# COMPRESS_ENABLED = True

# The url to be prepended to the static files. Used by the template engine
# to generate static urls to fetch the files from.
STATIC_URL = "static/"
# COMPRESS_URL = STATIC_URL

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)

# Additional files to look for when STATICFILES_FINDERS can't find a file
# This is a good setting for 3rd party files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

# Media storage configuration

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {"location": os.path.join(BASE_DIR, "media")},
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Hashids salt
HASHIDS_SALT = os.getenv("HASHIDS_SALT", default="1234")
HASHIDS_MIN_ENCODED_LENGTH = 7

# Env url conf
BASE_URL = os.getenv("BASE_URL", default="http://localhost:8000")


CELERY_BROKER_URL = os.getenv("REDIS_URL", default="redis://")



# Django Allauth
LOGIN_URL = "account_login"
LOGOUT_REDIRECT_URL = "account_login"
LOGIN_REDIRECT_URL = "sales:client_table"

# Requires the user email to login
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = {"email*", "password1*", "password2*"}
ACCOUNT_EMAIL_VERIFICATION = "mandatory"



# Session config
APPLICATION_PORTAL_SESSION_EXPIRY = 24 * 60 * 60  # 1 day

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"


# Twilio
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_NUMBER = os.getenv("TWILIO_NUMBER", "")

# Telegram
TELEGRAM_EXCEPTION_BOT_ID = env("TELEGRAM_EXCEPTION_BOT_ID", default="")
TELEGRAM_ADMIN_CHAT_IDS = env.list("TELEGRAM_ADMIN_CHAT_IDS", default=[])

# Cache backend is optional, but recommended to speed up user agent parsing
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "127.0.0.1:11211",
    }
}

# Name of cache backend to cache user agents. If it not specified default
# cache alias will be used. Set to `None` to disable caching.
USER_AGENTS_CACHE = "default"


GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", default="")

# User invite token
INVITE_TOKEN_EXPIRY_DAYS = os.getenv("INVITE_TOKEN_EXPIRY_DAYS", default=14)

USER_DATA_RETENTION_PERIOD = 3  # months

# Django Encryption Fields
""" Generating a new key
import os
import base64

new_key = base64.urlsafe_b64encode(os.urandom(32))
print(new_key)
"""
FIELD_ENCRYPTION_KEY = os.getenv(
    "FIELD_ENCRYPTION_KEY", "VbE3US6QQFLVsP-rv2_GUb9A7FVNqHTqBsRIHwVkyQE="
)

# OTP
OTP_EXPIRY_MIN = os.getenv("OTP_EXPIRY_MIN", default=10)

# LLM settings
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

MAX_APPLICATION_FORMS = 15


DEFAULT_EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", default=DEFAULT_EMAIL_BACKEND)
EMAIL_HOST = os.getenv("EMAIL_HOST", default="smtp.zeptomail.com")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", default="")


DJANGO_TABLES2_TABLE_ATTRS = {
    "class": "table-fixed w-full text-sm text-left rtl:text-right text-gray-500",
    "thead": {"class": "text-xs text-gray-700 uppercase bg-gray-100"},
    "th": {"class": "px-6 py-3"},
    "td": {"class": "px-6 py-4 overflow-hidden hover:overflow-visible text-ellipsis"},
}
DJANGO_TABLES2_TEMPLATE = "table.html"